# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20180418_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_name',
            new_name='user',
        ),
    ]
